on:
  push:
    branches:    
      - 'master'

name: 'Tests'

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v6
      - name: Install development dependencies
        run: |
          sudo apt-get update > /dev/null
          sudo apt-get install -qq build-essential > /dev/null
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          target: x86_64-unknown-linux-gnu
          default: true
          profile: minimal
      - name: Execute unit tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p larz --all-targets --all-features --future-incompat-report
      - name: Execute documentation tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --doc -p larz --all-features --future-incompat-report -- --show-output