on:
  schedule:
    - cron: '0 0 * * 0'

name: Update dependencies

jobs:
  code_check:
    name: Update dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy, rustfmt
          profile: minimal
      - name: Install 'cargo-edit'
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-edit
      - name: Upgrade dependencies
        uses: actions-rs/cargo@v1
        with:
          command: upgrade
      - name: Update lock file
        uses: actions-rs/cargo@v1
        with:
          command: update
      - name: Check if code still compiles
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all-targets --release
      - name: Commit changes, if any
        run: |
          git config --global user.name 'larz'
          git config --global user.email 'Dirout@users.noreply.github.com'
          git diff --quiet && git diff --staged --quiet || git commit -am "Automatically update dependencies"
          git push
